### ISSUE TITLE
Localizer is crashing with grunt-locales 7.0.3

### ISSUE THREAD

**Issue by florianduros** [jokesterfr/localizer#1]
Hello,

I'm trying to use the localizer v0.2.10 with grunt-locales 7.0.3.
Sadly, the localizer raises an error when I'm using a string with spaces.

Example  : 

```
localize('My string with spaces');
```

And i have this error at line 169 :

```
TypeError: func is not a function
```

Thanx !

**Comment by cdesiles** [comment]
Hi Ormazz,
could you tell this was working with a previous grunt-locales version?

**Comment by florianduros** [comment]
Hi,

Yes, it works with grunt-locales <= 6.1.0.

**Comment by cdesiles** [comment]
Ok, I don't have much time to investigate it at the moment, could you provide us a PR?
